package config
{
   public class HouseConfig
   {
      
      public static const GARAGE_ID:int = 1;
      
      private static var dataObj:Object = {
         "enabled":true,
         "rooms":[{
            "id":1,
            "defaultCoord":[11,8],
            "drop_limits":{
               "MIN_DROP_X":7,
               "MAX_DROP_X":18,
               "MIN_DROP_Y":3,
               "MAX_DROP_Y":12
            },
            "customAttributes":[{
               "type":"background",
               "data":"privateRoom"
            },{
               "type":"bounds",
               "data":"-320"
            }],
            "sceneObjects":[{
               "name":"",
               "coord":[19,6],
               "size":[1,1],
               "link":{
                  "id":-100,
                  "destCoord":[7,5],
                  "customAttributes":[{
                     "type":"label",
                     "data":"SALIR"
                  },{
                     "type":"direction",
                     "data":"8"
                  },{
                     "type":"hitHeight",
                     "data":"120"
                  },{
                     "type":"hitWidth",
                     "data":"140"
                  },{
                     "type":"hitX",
                     "data":"2"
                  },{
                     "type":"hitY",
                     "data":"-60"
                  }]
               }
            },{
               "name":"privateRoom.paredA1_so",
               "coord":[15,12],
               "size":[1,1]
            },{
               "name":"privateRoom.paredA2_so",
               "coord":[15,3],
               "size":[1,1]
            },{
               "name":"privateRoom.cantero_so",
               "coord":[15,3],
               "size":[1,7]
            },{
               "name":"privateRoom.doorUp_so",
               "coord":[6,9],
               "size":[1,1],
               "link":{
                  "id":4,
                  "destCoord":[10,5],
                  "customAttributes":[{
                     "type":"label",
                     "data":"SUBIR"
                  },{
                     "type":"direction",
                     "data":"0"
                  },{
                     "type":"hitHeight",
                     "data":"120"
                  },{
                     "type":"hitWidth",
                     "data":"60"
                  },{
                     "type":"hitX",
                     "data":"0"
                  },{
                     "type":"hitY",
                     "data":"-120"
                  }]
               }
            },{
               "name":"privateRoom.doorLeft_so",
               "coord":[6,5],
               "size":[1,1],
               "link":{
                  "id":2,
                  "destCoord":[21,9],
                  "customAttributes":[{
                     "type":"label",
                     "data":"HABITACION"
                  },{
                     "type":"direction",
                     "data":"4"
                  },{
                     "type":"hitHeight",
                     "data":"120"
                  },{
                     "type":"hitWidth",
                     "data":"60"
                  },{
                     "type":"hitX",
                     "data":"0"
                  },{
                     "type":"hitY",
                     "data":"-120"
                  }]
               }
            }]
         },{
            "id":2,
            "defaultCoord":[18,9],
            "drop_limits":{
               "MIN_DROP_X":14,
               "MAX_DROP_X":20,
               "MIN_DROP_Y":3,
               "MAX_DROP_Y":12
            },
            "customAttributes":[{
               "type":"background",
               "data":"privateRoom1"
            },{
               "type":"bounds",
               "data":"-800"
            }],
            "sceneObjects":[{
               "name":"privateRoom.doorUp_so",
               "coord":[13,8],
               "size":[1,1],
               "link":{
                  "id":5,
                  "destCoord":[14,5],
                  "customAttributes":[{
                     "type":"label",
                     "data":"SUBIR"
                  },{
                     "type":"direction",
                     "data":"0"
                  },{
                     "type":"hitHeight",
                     "data":"120"
                  },{
                     "type":"hitWidth",
                     "data":"60"
                  },{
                     "type":"hitX",
                     "data":"0"
                  },{
                     "type":"hitY",
                     "data":"-120"
                  }]
               }
            },{
               "name":"privateRoom.doorLeft_so",
               "coord":[13,4],
               "size":[1,1],
               "link":{
                  "id":3,
                  "destCoord":[20,8,9],
                  "customAttributes":[{
                     "type":"label",
                     "data":"HABITACION"
                  },{
                     "type":"direction",
                     "data":"4"
                  },{
                     "type":"hitHeight",
                     "data":"120"
                  },{
                     "type":"hitWidth",
                     "data":"60"
                  },{
                     "type":"hitX",
                     "data":"0"
                  },{
                     "type":"hitY",
                     "data":"-120"
                  }]
               }
            },{
               "name":"",
               "coord":[23,11],
               "size":[1,1],
               "link":{
                  "id":1,
                  "destCoord":[7,6],
                  "customAttributes":[{
                     "type":"label",
                     "data":"HABITACION"
                  },{
                     "type":"direction",
                     "data":"8"
                  },{
                     "type":"hitHeight",
                     "data":"150"
                  },{
                     "type":"hitWidth",
                     "data":"120"
                  },{
                     "type":"hitX",
                     "data":"0"
                  },{
                     "type":"hitY",
                     "data":"-120"
                  }]
               }
            },{
               "name":"privateRoom.doorSotano_so",
               "coord":[21,5],
               "size":[1,1],
               "link":{
                  "id":7,
                  "destCoord":[21,11],
                  "customAttributes":[{
                     "type":"label",
                     "data":"BAJAR"
                  },{
                     "type":"direction",
                     "data":"32"
                  },{
                     "type":"hitHeight",
                     "data":"100"
                  },{
                     "type":"hitWidth",
                     "data":"120"
                  },{
                     "type":"hitX",
                     "data":"0"
                  },{
                     "type":"hitY",
                     "data":"-90"
                  }]
               }
            }]
         },{
            "id":3,
            "defaultCoord":[17,8],
            "drop_limits":{
               "MIN_DROP_X":3,
               "MAX_DROP_X":20,
               "MIN_DROP_Y":3,
               "MAX_DROP_Y":12
            },
            "customAttributes":[{
               "type":"background",
               "data":"privateRoom2"
            },{
               "type":"bounds",
               "data":""
            }],
            "sceneObjects":[{
               "name":"",
               "coord":[22,7],
               "size":[1,1],
               "link":{
                  "id":2,
                  "destCoord":[14,4],
                  "customAttributes":[{
                     "type":"label",
                     "data":"HABITACION"
                  },{
                     "type":"direction",
                     "data":"8"
                  },{
                     "type":"hitHeight",
                     "data":"250"
                  },{
                     "type":"hitWidth",
                     "data":"120"
                  },{
                     "type":"hitX",
                     "data":"0"
                  },{
                     "type":"hitY",
                     "data":"-120"
                  }]
               }
            },{
               "name":"privateRoom.doorTreeUp_so",
               "coord":[7,2],
               "size":[1,1],
               "link":{
                  "id":8,
                  "destCoord":[18,9],
                  "customAttributes":[{
                     "type":"label",
                     "data":"SUBIR"
                  },{
                     "type":"direction",
                     "data":"0"
                  },{
                     "type":"hitHeight",
                     "data":"120"
                  },{
                     "type":"hitWidth",
                     "data":"60"
                  },{
                     "type":"hitX",
                     "data":"0"
                  },{
                     "type":"hitY",
                     "data":"-120"
                  }]
               }
            }]
         },{
            "id":4,
            "defaultCoord":[13,8],
            "drop_limits":{
               "MIN_DROP_X":10,
               "MAX_DROP_X":16,
               "MIN_DROP_Y":3,
               "MAX_DROP_Y":12
            },
            "customAttributes":[{
               "type":"background",
               "data":"privateRoomUp1"
            },{
               "type":"bounds",
               "data":"-505"
            }],
            "sceneObjects":[{
               "name":"privateRoom.baranda1_so",
               "coord":[18,12],
               "size":[1,1]
            },{
               "name":"privateRoom.baranda2_so",
               "coord":[20,4],
               "size":[1,1]
            },{
               "name":"privateRoom.doorDown_so",
               "coord":[9,4],
               "size":[1,1],
               "link":{
                  "id":1,
                  "destCoord":[7,9],
                  "customAttributes":[{
                     "type":"label",
                     "data":"BAJAR"
                  },{
                     "type":"direction",
                     "data":"32"
                  },{
                     "type":"hitHeight",
                     "data":"120"
                  },{
                     "type":"hitWidth",
                     "data":"60"
                  },{
                     "type":"hitX",
                     "data":"0"
                  },{
                     "type":"hitY",
                     "data":"-120"
                  }]
               }
            },{
               "name":"privateRoom.doorLeft_so",
               "coord":[9,8],
               "size":[1,1],
               "link":{
                  "id":5,
                  "destCoord":[20,7],
                  "customAttributes":[{
                     "type":"label",
                     "data":"HABITACION"
                  },{
                     "type":"direction",
                     "data":"4"
                  },{
                     "type":"hitHeight",
                     "data":"120"
                  },{
                     "type":"hitWidth",
                     "data":"60"
                  },{
                     "type":"hitX",
                     "data":"0"
                  },{
                     "type":"hitY",
                     "data":"-120"
                  }]
               }
            },{
               "name":"privateRoom.stairsAttic_so",
               "coord":[11,3],
               "size":[1,1],
               "link":{
                  "id":12,
                  "destCoord":[17,8],
                  "customAttributes":[{
                     "type":"label",
                     "data":"ATICO"
                  },{
                     "type":"direction",
                     "data":"0"
                  },{
                     "type":"hitHeight",
                     "data":"120"
                  },{
                     "type":"hitWidth",
                     "data":"60"
                  },{
                     "type":"hitX",
                     "data":"0"
                  },{
                     "type":"hitY",
                     "data":"-120"
                  }]
               }
            }]
         },{
            "id":5,
            "defaultCoord":[17,8],
            "drop_limits":{
               "MIN_DROP_X":14,
               "MAX_DROP_X":20,
               "MIN_DROP_Y":3,
               "MAX_DROP_Y":12
            },
            "customAttributes":[{
               "type":"background",
               "data":"privateRoomUp2"
            },{
               "type":"bounds",
               "data":"-800"
            }],
            "sceneObjects":[{
               "name":"privateRoom.doorDown_so",
               "coord":[13,4],
               "size":[1,1],
               "link":{
                  "id":2,
                  "destCoord":[7,9],
                  "customAttributes":[{
                     "type":"label",
                     "data":"BAJAR"
                  },{
                     "type":"direction",
                     "data":"32"
                  },{
                     "type":"hitHeight",
                     "data":"120"
                  },{
                     "type":"hitWidth",
                     "data":"60"
                  },{
                     "type":"hitX",
                     "data":"0"
                  },{
                     "type":"hitY",
                     "data":"-120"
                  }]
               }
            },{
               "name":"privateRoom.doorLeft_so",
               "coord":[13,8],
               "size":[1,1],
               "link":{
                  "id":6,
                  "destCoord":[21,7],
                  "customAttributes":[{
                     "type":"label",
                     "data":"HABITACION"
                  },{
                     "type":"direction",
                     "data":"4"
                  },{
                     "type":"hitHeight",
                     "data":"120"
                  },{
                     "type":"hitWidth",
                     "data":"60"
                  },{
                     "type":"hitX",
                     "data":"0"
                  },{
                     "type":"hitY",
                     "data":"-120"
                  }]
               }
            },{
               "name":"",
               "coord":[22,7],
               "size":[1,1],
               "link":{
                  "id":4,
                  "destCoord":[10,9],
                  "customAttributes":[{
                     "type":"label",
                     "data":"HABITACION"
                  },{
                     "type":"direction",
                     "data":"8"
                  },{
                     "type":"hitHeight",
                     "data":"250"
                  },{
                     "type":"hitWidth",
                     "data":"120"
                  },{
                     "type":"hitX",
                     "data":"0"
                  },{
                     "type":"hitY",
                     "data":"-120"
                  }]
               }
            }]
         },{
            "id":6,
            "defaultCoord":[16,8],
            "drop_limits":{
               "MIN_DROP_X":15,
               "MAX_DROP_X":20,
               "MIN_DROP_Y":3,
               "MAX_DROP_Y":12
            },
            "customAttributes":[{
               "type":"background",
               "data":"privateRoomUp3"
            },{
               "type":"bounds",
               "data":"-700"
            }],
            "sceneObjects":[{
               "name":"",
               "coord":[22,7],
               "size":[1,1],
               "link":{
                  "id":5,
                  "destCoord":[14,8],
                  "customAttributes":[{
                     "type":"label",
                     "data":"HABITACION"
                  },{
                     "type":"direction",
                     "data":"8"
                  },{
                     "type":"hitHeight",
                     "data":"250"
                  },{
                     "type":"hitWidth",
                     "data":"120"
                  },{
                     "type":"hitX",
                     "data":"0"
                  },{
                     "type":"hitY",
                     "data":"-120"
                  }]
               }
            }]
         },{
            "id":7,
            "defaultCoord":[17,8],
            "drop_limits":{
               "MIN_DROP_X":14,
               "MAX_DROP_X":18,
               "MIN_DROP_Y":3,
               "MAX_DROP_Y":12
            },
            "customAttributes":[{
               "type":"background",
               "data":"privateRoomDown7"
            },{
               "type":"bounds",
               "data":"-800"
            }],
            "sceneObjects":[{
               "name":"privateRoom.doorSotanoSube_so",
               "coord":[22,8],
               "size":[1,1],
               "link":{
                  "id":2,
                  "destCoord":[20,4],
                  "customAttributes":[{
                     "type":"label",
                     "data":"SUBIR"
                  },{
                     "type":"direction",
                     "data":"0"
                  },{
                     "type":"hitHeight",
                     "data":"120"
                  },{
                     "type":"hitWidth",
                     "data":"60"
                  },{
                     "type":"hitX",
                     "data":"0"
                  },{
                     "type":"hitY",
                     "data":"-120"
                  }]
               }
            }]
         },{
            "id":8,
            "defaultCoord":[18,8],
            "drop_limits":{
               "MIN_DROP_X":12,
               "MAX_DROP_X":17,
               "MIN_DROP_Y":3,
               "MAX_DROP_Y":10
            },
            "customAttributes":[{
               "type":"background",
               "data":"privateRoomTree"
            },{
               "type":"bounds",
               "data":"-800"
            }],
            "sceneObjects":[{
               "name":"privateRoom.doorTreeDown_so",
               "coord":[18,7],
               "size":[1,1],
               "link":{
                  "id":3,
                  "destCoord":[7,5],
                  "customAttributes":[{
                     "type":"label",
                     "data":"BAJAR"
                  },{
                     "type":"direction",
                     "data":"32"
                  },{
                     "type":"hitHeight",
                     "data":"150"
                  },{
                     "type":"hitWidth",
                     "data":"80"
                  },{
                     "type":"hitX",
                     "data":"0"
                  },{
                     "type":"hitY",
                     "data":"-160"
                  }]
               }
            },{
               "name":"privateRoom.tree_so",
               "coord":[14,5],
               "size":[1,1]
            }]
         },{
            "id":9,
            "defaultCoord":[17,8],
            "drop_limits":{
               "MIN_DROP_X":14,
               "MAX_DROP_X":18,
               "MIN_DROP_Y":3,
               "MAX_DROP_Y":12
            },
            "customAttributes":[{
               "type":"background",
               "data":"privateRoomGarage"
            },{
               "type":"bounds",
               "data":"-800"
            }],
            "sceneObjects":[]
         },{
            "id":10,
            "defaultCoord":[18,9],
            "drop_limits":{
               "MIN_DROP_X":3,
               "MAX_DROP_X":20,
               "MIN_DROP_Y":3,
               "MAX_DROP_Y":12
            },
            "customAttributes":[{
               "type":"background",
               "data":"privateRoomGranja"
            },{
               "type":"bounds",
               "data":""
            }],
            "sceneObjects":[{
               "name":"privateRoom.doorUp_so",
               "coord":[23,6],
               "size":[1,1],
               "link":{
                  "id":1,
                  "destCoord":[14,5],
                  "customAttributes":[{
                     "type":"label",
                     "data":"SUBIR"
                  },{
                     "type":"direction",
                     "data":"0"
                  },{
                     "type":"hitHeight",
                     "data":"120"
                  },{
                     "type":"hitWidth",
                     "data":"60"
                  },{
                     "type":"hitX",
                     "data":"0"
                  },{
                     "type":"hitY",
                     "data":"-120"
                  }]
               }
            }]
         },{
            "id":11,
            "defaultCoord":[17,8],
            "drop_limits":{
               "MIN_DROP_X":12,
               "MAX_DROP_X":22,
               "MIN_DROP_Y":4,
               "MAX_DROP_Y":12
            },
            "customAttributes":[{
               "type":"background",
               "data":"techo"
            },{
               "type":"bounds",
               "data":"-800"
            }],
            "sceneObjects":[{
               "name":"",
               "coord":[18,12],
               "size":[1,1],
               "link":{
                  "id":12,
                  "destCoord":[14,10],
                  "customAttributes":[{
                     "type":"label",
                     "data":"BAJAR"
                  },{
                     "type":"direction",
                     "data":"32"
                  },{
                     "type":"hitHeight",
                     "data":"40"
                  },{
                     "type":"hitWidth",
                     "data":"400"
                  },{
                     "type":"hitX",
                     "data":"0"
                  },{
                     "type":"hitY",
                     "data":"0"
                  }]
               }
            },{
               "name":"",
               "coord":[22,8],
               "size":[1,1],
               "link":{
                  "id":1,
                  "destCoord":[18,12],
                  "customAttributes":[{
                     "type":"label",
                     "data":"SALTAR"
                  },{
                     "type":"direction",
                     "data":"32"
                  },{
                     "type":"hitHeight",
                     "data":"100"
                  },{
                     "type":"hitWidth",
                     "data":"50"
                  },{
                     "type":"hitX",
                     "data":"2"
                  },{
                     "type":"hitY",
                     "data":"-60"
                  }]
               }
            }]
         },{
            "id":12,
            "defaultCoord":[17,8],
            "drop_limits":{
               "MIN_DROP_X":14,
               "MAX_DROP_X":22,
               "MIN_DROP_Y":4,
               "MAX_DROP_Y":12
            },
            "customAttributes":[{
               "type":"background",
               "data":"atico"
            },{
               "type":"bounds",
               "data":"-800"
            }],
            "sceneObjects":[{
               "name":"privateRoom.doorRoof_so",
               "coord":[13,9],
               "size":[1,1],
               "link":{
                  "id":11,
                  "destCoord":[18,9],
                  "customAttributes":[{
                     "type":"label",
                     "data":"SUBIR"
                  },{
                     "type":"direction",
                     "data":"0"
                  },{
                     "type":"hitHeight",
                     "data":"120"
                  },{
                     "type":"hitWidth",
                     "data":"60"
                  },{
                     "type":"hitX",
                     "data":"0"
                  },{
                     "type":"hitY",
                     "data":"-120"
                  }]
               }
            },{
               "name":"privateRoom.doorAttic_so",
               "coord":[21,8],
               "size":[1,1],
               "link":{
                  "id":4,
                  "destCoord":[7,10],
                  "customAttributes":[{
                     "type":"label",
                     "data":"BAJAR"
                  },{
                     "type":"direction",
                     "data":"32"
                  },{
                     "type":"hitHeight",
                     "data":"60"
                  },{
                     "type":"hitWidth",
                     "data":"120"
                  },{
                     "type":"hitX",
                     "data":"2"
                  },{
                     "type":"hitY",
                     "data":"-60"
                  }]
               }
            }]
         }]
      };
       
      
      public function HouseConfig()
      {
         super();
      }
      
      public static function get data() : Object
      {
         return dataObj;
      }
      
      public static function getRoomData(param1:int) : Object
      {
         var _loc2_:Object = null;
         for each(_loc2_ in data.rooms)
         {
            if(_loc2_.id == param1)
            {
               return _loc2_;
            }
         }
         return null;
      }
   }
}
